### ISSUE TITLE
Raw results?

### ISSUE THREAD

**Issue by laisimiao** [ZHU-Zhiyu/High-Rank_RGB-Event_Tracker#4]
Could you provide the raw results like in your paper?

and do you evaluate the MonTrack on COESOT or CEUTrack on FE108?

**Comment by ZHU-Zhiyu** [comment]
@laisimiao Raw results are in [here](https://drive.google.com/file/d/1jnjbM17lZn2vl7PIFCMd2A6pMOa5h35E/view?usp=drive_link). Actually, we have tried many times to cross-adapt those trackers; however, their performance is unsatisfactory. It may be due to the huge distribution gaps between those datasets. If any further question, feel free to ask.

**Comment by laisimiao** [comment]
Thanks. And is the event input form of MonTrack `voxel` ? If not, it is trouble to re-convert COESOT dataset to its specific form and evaluate.

**Comment by ZHU-Zhiyu** [comment]
@laisimiao It takes raw event cloud as input, correponding processing code as [here](https://github.com/ZHU-Zhiyu/High-Rank_RGB-Event_Tracker/blob/main/Utils/Evt_convert.py). [Here](https://drive.google.com/file/d/1qWMLD_PHH6IhzCsG943xwCQmkwnD9pyc/view?usp=drive_link) is one of our results for adapting MonTrack on COESOT, [code as here](https://drive.google.com/file/d/1uBNv4vQIL1p5Hf2uoMumX0zOJFrXJy8C/view?usp=drive_link).
